const tools = [
    {name: 'Brush', category: ['Painting'], checked: false},
    {name: 'Roller', category: ['Painting'], checked: false},
    {name: 'Spray Gun', category: ['Painting'], checked: false},
    {name: 'Spatula', category: ['Painting'], checked: false},
    {name: 'Mixer', category: ['Painting'], checked: false},
    {name: 'Tray', category: ['Painting'], checked: false},
    {name: 'Drop Cloth', category: ['Painting'], checked: false},
    {name: 'Tape', category: ['Painting'], checked: false},
    {name: 'Ladder', category: ['Painting'], checked: false},
    {name: 'Stencil', category: ['Painting'], checked: false},
    {name: 'Chisel', category: ['Finish Carpentry'], checked: false},
    {name: 'Plane', category: ['Finish Carpentry'], checked: false},
    {name: 'Saw', category: ['Finish Carpentry'], checked: false},
    {name: 'Sandpaper', category: ['Finish Carpentry'], checked: false},
    {name: 'Clamp', category: ['Finish Carpentry'], checked: false},
    {name: 'Square', category: ['Finish Carpentry'], checked: false},
    {name: 'Level', category: ['Finish Carpentry'], checked: false},
    {name: 'Mallet', category: ['Finish Carpentry'], checked: false},
    {name: 'Dowel', category: ['Finish Carpentry'], checked: false},
    {name: 'File', category: ['Finish Carpentry'], checked: false},
    {name: 'Hammer', category: ['Framing'], checked: false},
    {name: 'Nail Gun', category: ['Framing'], checked: false},
    {name: 'Stapler', category: ['Framing'], checked: false},
    {name: 'Sawhorse', category: ['Framing'], checked: false},
    {name: 'Level', category: ['Framing'], checked: false},
    {name: 'Square', category: ['Framing'], checked: false},
    {name: 'Measuring Tape', category: ['Framing'], checked: false},
    {name: 'Stud Finder', category: ['Framing'], checked: false},
    {name: 'Chalk Line', category: ['Framing'], checked: false},
    {name: 'Utility Knife', category: ['Framing'], checked: false},
    {name: 'Angle Grinder', category: ['Finish Carpentry'], checked: false},
    {name: 'Belt Sander', category: ['Finish Carpentry'], checked: false},
    {name: 'Coping Saw', category: ['Finish Carpentry'], checked: false},
    {name: 'Corner Clamp', category: ['Finish Carpentry'], checked: false},
    {name: 'Dust Extractor', category: ['Finish Carpentry', 'Painting'], checked: false},
    {name: 'Edge Planer', category: ['Finish Carpentry'], checked: false},
    {name: 'Flap Sander', category: ['Finish Carpentry'], checked: false},
    {name: 'Flooring Nailer', category: ['Finish Carpentry'], checked: false},
    {name: 'Framing Square', category: ['Framing'], checked: false},
    {name: 'Joist Hanger', category: ['Framing'], checked: false},
    {name: 'Laser Level', category: ['Framing', 'Finish Carpentry'], checked: false},
    {name: 'Oscillating Multi-Tool', category: ['Finish Carpentry'], checked: false},
    {name: 'Pipe Clamp', category: ['Finish Carpentry'], checked: false},
    {name: 'Plunge Router', category: ['Finish Carpentry'], checked: false},
    {name: 'Pocket Hole Jig', category: ['Finish Carpentry'], checked: false},
    {name: 'Rotary Tool', category: ['Finish Carpentry'], checked: false},
    {name: 'Sheet Sander', category: ['Finish Carpentry'], checked: false},
    {name: 'Speed Square', category: ['Framing'], checked: false},
    {name: 'Spiral Saw', category: ['Finish Carpentry'], checked: false},
    {name: 'Track Saw', category: ['Finish Carpentry'], checked: false},
    {name: 'Trim Router', category: ['Finish Carpentry'], checked: false},
    {name: 'Wood Chisel Set', category: ['Finish Carpentry'], checked: false},
    {name: 'Workbench', category: ['Finish Carpentry', 'Framing'], checked: false},
    {name: 'Zirconia Belts', category: ['Finish Carpentry'], checked: false},
    {name: 'Scaffold', category: ['Painting', 'Framing'], checked: false},
    {name: 'Scraper', category: ['Painting'], checked: false},
    {name: 'Paint Mixer', category: ['Painting'], checked: false},
    {name: 'Caulking Gun', category: ['Painting', 'Finish Carpentry'], checked: false},
    {name: 'Paint Strainer', category: ['Painting'], checked: false},
    {name: 'Wallpaper Steamer', category: ['Painting'], checked: false}
];

module.exports = tools